---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MilhoNerfado.
--- DateTime: 07/05/24 17:00
---

require("scope")

-- Validates if esp-idf is available
local function check_esp_idf()
	local _, stderr = scope.exec("idf.py")
	return stderr ~= nil
end

function serial_rx(msg) end

function user_command(arg_list)
	if not check_esp_idf() then
		scope.eprintln("esp-idf not found, try exporting esp-idf environment variables first")
		return
	end

	local cmd = "idf.py " .. table.concat(arg_list, " ")

	if arg_list[2] == "flash" or "monitor" then
		scope.disconnect()
		scope.exec(cmd)
		scope.connect()
	end
end
