---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by matheuswhite.
--- DateTime: 23/01/24 18:49
---

require "scope"

function serial_rx(msg)
    scope.connect('/dev/ttyACM0', 115200)
    scope.disconnect()
    scope.serial_tx(msg)
    scope.println('Sent ' .. bytes2str(msg))
    scope.eprintln('Timeout')
end

function user_command(arg_list)
    scope.connect('/dev/ttyACM0', 115200)
    scope.disconnect()
    scope.serial_tx(str2bytes(arg_list[1]))
    scope.println('Sent ' .. arg_list[2])
    scope.eprintln('Timeout')
end
