---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by matheuswhite.
--- DateTime: 26/02/24 21:00
---

require "scope"

function check_zephyr_base()
    local pipe = io.popen('echo $ZEPHYR_BASE')
    local content = pipe:read('*all')
    pipe:close()
    return content ~= nil and content ~= '' and content ~= '\n'
end

function serial_rx(msg)
end

function user_command(arg_list)
    if not check_zephyr_base() then
        scope.eprintln('$ZEPHYR_BASE is empty')
        return
    end

    scope.run_processes('west ' .. table.concat(arg_list, ' '), 'source $ZEPHYR_BASE/../.venv/bin/activate')
end